### ISSUE TITLE
Issue with the DOS

### ISSUE THREAD

**Issue by giovannipizzi** [aiidalab/widget-bandsplot#24] opened 2022-09-06 09:39 UTC
When checking the binder example, if I only show the 's' channel, there is clearly something wrong with the plot (see energy range 0-6eV).
Can you check why and fix?

<img width="1340" alt="issue" src="https://user-images.githubusercontent.com/16132028/188601852-5c726f41-c0b2-42ae-be70-bea97734d6c4.png">

**Comment by dou-du** [comment] 2022-09-09 14:59
> When checking the binder example, if I only show the 's' channel, there is clearly something wrong with the plot (see energy range 0-6eV). Can you check why and fix?
> 
> <img alt="issue" width="1340" src="https://user-images.githubusercontent.com/16132028/188601852-5c726f41-c0b2-42ae-be70-bea97734d6c4.png">

This issue is a bit strange. There is no problem for the horizontal figure. I check the codes and do not find any error in the codes. I believe this is a bug from the chart.js. I will open a issue and ask for help.

**Comment by dou-du** [comment] 2022-09-15 12:26
Try the new binder link with the fixed widgets.

**Comment by unkcpz** [comment] 2023-01-30 15:25
Hi @dou-du, it seems we still have this issue with the widget running in QeApp, we use the version `0.5.0` and get the image below.
![image](https://user-images.githubusercontent.com/8831685/215519085-fd75dcfa-bc2d-411d-bc23-d0bdb2d034a9.png)

**Comment by dou-du** [comment] 2023-01-31 05:54
> In my opinion, as you said you are working on updating the chart.js, we need to try to get it finished and use the latest version of it. There are some compatible version tags with the JS files, I fixed some of then but since I am not familiar with JS package control, it is for sure some issue remains. Could you take time to look after it?

Sure, I will take care of it. However, this may take some time to get it done.

**Comment by unkcpz** [comment] 2023-01-31 09:52
@dou-du thanks, and don't worry if you need time to get it done. I highly suggest you can write in the AiiDAlab roadmap and synchronous it to our biweekly meeting notes and give it an estimated DDL (Please check the email I sent yesterday). I'll be the 2nd RP and help you to get it done in time.

**Comment by unkcpz** [comment] 2023-02-01 14:23
@dou-du mentioned in the meeting that he is not able to reproduce the issue with the binder link. I and not care about the binder, it is only for the showcase. Can you use the same data, the JSON file in the repo, and plot the band structure and dos in jupyter notebook. If you cannot reproduce it again, let me know. The data generated is the QeApp is the same as the one in this repo.

**Comment by unkcpz** [comment] 2023-02-01 14:34
The reason @dou-du cannot reproduce maybe that in the AiiDAlab we have to use the legacy notebook backend rather than the jupyterlab. Can you confirm that the widget works all good in the legacy notebook backend?

**Comment by dou-du** [comment] 2023-02-02 02:13
> The reason @dou-du cannot reproduce maybe that in the AiiDAlab we have to use the legacy notebook backend rather than the jupyterlab. Can you confirm that the widget works all good in the legacy notebook backend?

Thanks! This is a very good point. I checked the widget both in Jupyter notebook and JupyterLab environment. It is working fine in the JupyterLab. However, the widget is not even showing in the Jupyter notebook. I suspected something strange happening. I am going to check it.

**Comment by dou-du** [comment] 2023-02-02 07:19
@unkcpz could you check the "widget-bandsplot" version in the QE app from terminal with "pip freeze | grep widget-bandsplot"? Thanks!

**Comment by unkcpz** [comment] 2023-02-02 08:48
The version is the latest 0.5.0
Now we have THEOS Aiidalab deployment, it should be very easy to get the same test/develop environment by just go there.

**Comment by dou-du** [comment] 2023-02-02 11:41
> The version is the latest 0.5.0 Now we have THEOS Aiidalab deployment, it should be very easy to get the same test/develop environment by just go there.

I just register materials cloud account. Could you add me to the Aiidalab?

**Comment by unkcpz** [comment] 2023-02-02 12:06
No, the new deployment for THEOS is http://theospc7.epfl.ch/ go there and sign up. Hopefully, you can check the theos mailing list carefully.

**Comment by unkcpz** [comment] 2023-02-15 16:06
The issue of small jump in total dos is open at https://github.com/aiidalab/widget-bandsplot/issues/49, so I'll close this one since they look not exact the same.

**Closed by unkcpz** 2023-02-15 16:06 UTC
Labels: bug, Fixed
